### ISSUE TITLE
Time formats precision

### ISSUE THREAD

**Issue by mistic100** [rainmeter/rainmeter-docs#12]
This follows my investigations here https://forum.rainmeter.net/viewtopic.php?f=5&t=32019

The Time measure uses `strftime` for formatting and `get_time` for parsing. These two functions don't have exactly the same format support, more specifically, `get_time` does not support `%z` and `%Z` (perhaps there are some other differences, I didn't check everything).

I think this should be made clear in the doc which currently states under "Format codes" 
> The following formatting codes are used in the Format and TimeStampFormat options.

https://en.cppreference.com/w/cpp/io/manip/get_time
https://en.cppreference.com/w/cpp/chrono/c/strftime

**Comment by brianferguson** [comment]
Thanks! Sorry it took so long.

-Brian
