### ISSUE TITLE
Wrong exclusion of general image options in skins/rainmeter?

### ISSUE THREAD

**Issue by thatsIch** [rainmeter/rainmeter-docs#3]
I am currently programming the auto-completion plugin for ST3 and I noticed a part in the documentation where it states [1]

> **General image options**
> All [general image options](https://docs.rainmeter.net/manual-beta/meters/general-options/image-options/) are valid for Background except **Tile**, which is handled with BackgroundMode.

and when going there [2] there is no section for `Tile`. Am I missing something?

I just wanted to ask before PRing that

---

[1] https://docs.rainmeter.net/manual-beta/skins/rainmeter-section/
[2] https://docs.rainmeter.net/manual-beta/meters/general-options/image-options/

**Comment by jsmorley** [comment]
Ah, documentation failure. https://docs.rainmeter.net/manual/meters/image/#Tile is an option for the Image meter, not a general image option. I'll fix it.

**Comment by thatsIch** [comment]
I did not see any changes in the documentations
- So all [image meter options](https://docs.rainmeter.net/manual/meters/image/) are valid (that includes general meter options + general image options)?
- general image options but Tile is not excluded (since it does not exist there anyways)?

**Comment by jsmorley** [comment]
Removed reference to "Tile" as an exception to BackgroundMode, as Tile is not a General Image Option, but specific to the Image meter.

**Comment by thatsIch** [comment]
Thank you very much for the clarification! That makes it a lot easier to implement 👍
