### ISSUE TITLE
Small change to HWINFO site

### ISSUE THREAD

**Issue by CrazyWolf13** [rainmeter/rainmeter-docs#41]
https://docs.rainmeter.net/tips/hwinfo/
Here on the first image, `Show sensors on startup` should be ticked, otherwise it won't work. 
Thank you Jeff and Reisir for the help.

**Comment by jsmorley** [comment]
I'm not sure I follow. It works fine for me without having that checked.
![1](https://user-images.githubusercontent.com/1533041/213812465-8a9be8d5-10d2-4def-b714-fe8f084cb3f9.png)

**Comment by CrazyWolf13** [comment]
> I'm not sure I follow. It works fine for me without having that checked.
> ![1](https://user-images.githubusercontent.com/1533041/213812465-8a9be8d5-10d2-4def-b714-fe8f084cb3f9.png)
> 

On my end it was required, otherwise i had to manually open the sensors tab once by right clicking the tray icon, on startup. The Reisir and Jeff told me to check this and i should make an issue request here...

**Comment by jsmorley** [comment]
If the intent is to have the sensors dialog open on startup, then yes. You would want to check that "Show Sensors on Startup" box. However, I personally can't see why you would want that, and I certainly don't want to change the docs to recommend it.

**Comment by CrazyWolf13** [comment]
> If the intent is to have the sensors dialog open on startup, then yes. You would want to check that "Show Sensors on Startup" box. However, I personally can't see why you would want that, and I certainly don't want to change the docs to recommend it.
> 

No, the sensors didn't start up for me on startup, i did everything like in the guide then i asked in the rainmeter dc and Reisir and Jeff, they told me to enabled this, and after this it worked on startup. They also told me i should report it here so it can be updated, cause it's an error. 
I don't know what is correct here, they just told me so, and after i did the change it worked for me so i assume it has to correct to change the guide.

**Comment by CrazyWolf13** [comment]
> If the intent is to have the sensors dialog open on startup, then yes. You would want to check that "Show Sensors on Startup" box. However, I personally can't see why you would want that, and I certainly don't want to change the docs to recommend it.
> 

You have the minimize sensors on startup ticked, so they surely won't display 😂
