### ISSUE TITLE
shape ellipse example wrong?

### ISSUE THREAD

**Issue by thatsIch** [rainmeter/rainmeter-docs#7]
In https://docs.rainmeter.net/manual-beta/meters/shape/#Ellipse it states that

* `CenterX`
* `CenterY`
* `RadiusX`

are required, but the first example only uses 2 values `Shape=Ellipse 50,50`. Is the example wrong or the required state of `RadiusX`?

**Comment by brianferguson** [comment]
The example was wrong. At least 1 radius value is required. Thanks for reporting.
