### ISSUE TITLE
Documentation question about Mouse Actions in [Rainmeter] section

### ISSUE THREAD

**Issue by thatsIch** [rainmeter/rainmeter-docs#8]
On 

https://docs.rainmeter.net/manual-beta/mouse-actions/

it states:

> In the [Rainmeter] section of the skin if Background is defined.

I noticed, that it works even without defining a Background e.g. just clicking the letter of a string meter is sufficient

Cheers, Ich

**Comment by jsmorley** [comment]
Ok, tweaked. Thanks for reporting.
